
export default [
  // { key: 'auto', lang: '自动检测' },
  // { key: 'zh', lang: '中文' },
  { key: 'en', lang: '英语' },
  { key: 'jp', lang: '日语' },
  { key: 'kor', lang: '韩语' },
  { key: 'fra', lang: '法语' },
  { key: 'ru', lang: '俄语' },
  { key: 'de', lang: '德语' },
  { key: 'it', lang: '意大利语' },
  { key: 'spa', lang: '西班牙语' },
  { key: 'pt', lang: '葡萄牙语' },
  { key: 'th', lang: '泰语' },
  { key: 'ara', lang: '阿拉伯语' },
  { key: 'el', lang: '希腊语' },
  { key: 'nl', lang: '荷兰语' },
  { key: 'fin', lang: '芬兰语' },
  { key: 'swe', lang: '瑞典语' },
  // { key: 'pl', lang: '波兰语' },
  // { key: 'dan', lang: '丹麦语' },
  // { key: 'bul', lang: '保加利亚语' },
  // { key: 'est', lang: '爱沙尼亚语' },
  // { key: 'cs', lang: '捷克语' },
  // { key: 'rom', lang: '罗马尼亚语' },
  // { key: 'slo', lang: '斯洛文尼亚语' },
  // { key: 'swe', lang: '瑞典语' },
  // { key: 'hu', lang: '匈牙利语' },
  // { key: 'vie', lang: '越南语' },
  // { key: 'cht', lang: '繁体中文' },
  // { key: 'yue', lang: '粤语' },
  // { key: 'wyw', lang: '文言文' },
];
